name: graph
description: Graph component of the SBB Graphs package.
publish_to: 'none'
version: 1.0.0
homepage: https://github.com/SchweizerischeBundesbahnen/sbb-graphs


environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # https://pub.dev/packages/antlr4
  antlr4: ^4.11.1
  # https://pub.dev/packages/collection
  collection: ^1.16.0
  # https://pub.dev/packages/logging
  logging: ^1.0.2
  # https://pub.dev/packages/meta
  meta: ^1.7.0
  # https://pub.dev/packages/vector_math
  vector_math: ^2.1.3

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^2.0.0
  # https://pub.dev/packages/test
  test: ^1.21.5
